version: 1
build:
  ldflags:
    - -X github.com/crescent-network/crescent/v3/x/farming/keeper.enableAdvanceEpoch=true
    - -X github.com/crescent-network/crescent/v3/x/liquidfarming/keeper.enableAdvanceAuction=true
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
accounts:
  - name: alice
    coins:
      - 1500000000000stake
      - 1000000000000000uatom
      - 1000000000000000uusd
    mnemonic:
      guard cream sadness conduct invite crumble clock pudding hole grit liar
      hotel maid produce squeeze return argue turtle know drive eight casino maze host
  - name: bob
    coins:
      - 1000000000000stake
      - 1000000000000000uatom
      - 1000000000000000uusd
    mnemonic:
      friend excite rough reopen cover wheel spoon convince island path clean
      monkey play snow number walnut pull lock shoot hurry dream divide concert discover
  - name: steve
    coins:
      - 1000000000000stake
      - 1000000000000000uatom
      - 1000000000000000uusd
    mnemonic:
      fuel obscure melt april direct second usual hair leave hobby beef bacon
      solid drum used law mercy worry fat super must ritual bring faculty
  - name: source
    coins:
      - 15000000000000airdrop
    mnemonic:
      diary behind allow lawn loop assault armor survey media toe rural mass
      skull way crater tobacco pair glare window soon lift pistol fitness annual
faucet:
  name: bob
  coins:
    - 10000000stake
    - 10000000uatom
  host: 0.0.0.0:4500
validators:
  - name: alice
    bonded: 100000000stake
    home: $HOME/.crescent
    app:
      api:
        address: :1317
      grpc:
        address: :9094
      grpc-web:
        address: :9095
    config:
      p2p:
        laddr: :26660
      rpc:
        laddr: :26661
        pprof_laddr: :6062
genesis:
  chain_id: localnet
  app_state:
    budget:
      params:
        budgets:
          - destination_address: cre1ddn66jv0sjpmck0ptegmhmqtn35qsg2vxyk2hn9sqf4qxtzqz3sq3qhhde
            end_time: "2030-03-01T00:00:00Z"
            name: incentivize-marketmaker-20201Q-20301Q
            rate: "0.300000000000000000"
            source_address: cre17xpfvakm2amg962yls6f84z3kell8c5l53s97s
            start_time: "2020-03-01T00:00:00Z"
    claim:
      airdrops:
        - conditions:
            - CONDITION_TYPE_DEPOSIT
            - CONDITION_TYPE_SWAP
            - CONDITION_TYPE_LIQUIDSTAKE
            - CONDITION_TYPE_VOTE
          end_time: "2022-05-21T00:00:00Z"
          id: "1"
          source_address: cre15rz2rwnlgr7nf6eauz52usezffwrxc0mxajpmw
          start_time: "2022-03-01T00:00:00Z"
      claim_records:
        - airdrop_id: "1"
          claimable_coins:
            - amount: "3000000000000"
              denom: airdrop
          claimed_conditions: null
          initial_claimable_coins:
            - amount: "3000000000000"
              denom: airdrop
          recipient: cre1zaavvzxez0elundtn32qnk9lkm8kmcszxclz6p
    crisis:
      constant_fee:
        denom: stake
    farming:
      params:
        private_plan_creation_fee:
          - amount: "100000"
            denom: stake
    gov:
      deposit_params:
        min_deposit:
          - amount: "1"
            denom: stake
      voting_params:
        voting_period: 20s
    liquidfarming:
      params:
        liquid_farms:
          - fee_rate: "0.000000000000000000"
            min_bid_amount: "1"
            min_farm_amount: "1"
            pool_id: "1"
        rewards_auction_duration: 120s
    liquidity:
      params:
        pair_creation_fee:
          - amount: "100000"
            denom: stake
        pool_creation_fee:
          - amount: "100000"
            denom: stake
    liquidstaking:
      params:
        liquid_bond_denom: bstake
        whitelisted_validators:
          - target_weight: "100000000"
            validator_address: crevaloper1zaavvzxez0elundtn32qnk9lkm8kmcszyvldht
    marketmaker:
      params:
        incentive_pairs:
          - incentive_weight: "0.000000000000000000"
            max_spread: "0"
            min_depth: "0"
            min_width: "0"
            pair_id: 1
            update_time: "2022-09-10T00:00:00Z"
          - incentive_weight: "0.000000000000000000"
            max_spread: "0"
            min_depth: "0"
            min_width: "0"
            pair_id: 2
            update_time: "2022-09-10T00:00:00Z"
    mint:
      params:
        mint_denom: stake
    staking:
      params:
        bond_denom: stake
